# Generated by Django 5.0.3 on 2024-08-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='ph_no',
        ),
    ]
